[a,b]=textread('cluster_data1.txt','%d %d');
[c,d]=textread('cluster_data2.txt','%d %d');
[e,f]=textread('cluster_data3.txt','%d %d');
[g,h]=textread('cluster_data4.txt','%d %d');
[i,j]=textread('cluster_data5.txt','%d %d');
scatter(a,b);
hold on;
scatter(c,d);
hold on;
scatter(e,f);
hold on;
scatter(g,h);
hold on;
scatter(i,j);
hold on;
TRI=delaunay(a,b);
triplot(TRI,a,b);
hold on;
TRI=delaunay(c,d);
triplot(TRI,c,d);
hold on;
TRI=delaunay(e,f);
triplot(TRI,e,f);
hold on;
TRI=delaunay(g,h);
triplot(TRI,g,h);
hold on;
TRI=delaunay(i,j);
triplot(TRI,i,j);